steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=cmd/pylonsd']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'hello']
  env: ['PROJECT_ROOT=cmd/pylonsd']
artifacts:
  objects:
    location: 'gs://pylons_node/'
    paths: ['.pylonsd']
