accounts:
  - name: alice
    coins: ["20000pylon", "200000000bedrock"]
  - name: bob
    coins: ["10000pylon", "100000000bedrock"]
validator:
  name: alice
  staked: "100000000bedrock"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5pylons", "100000bedrock"]
