version: '3'

services:
  node0:
    container_name: pylonsnode
    build:
      context: .
      args:
        - BINARY_VERSION=v1.0.0-rc2
    command: start.sh
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - ./debug:/debug