version: '3'

services:
  node0:
    container_name: pylonsnode
    build:
      context: .
      args:
        - BINARY_VERSION=v0.1.1
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - ./debug:/debug