version: '3'

services:
  node:
    container_name: pylonsnode
    build:
      context: .
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - ./debug:/debug
      - trace:/tmp/trace
  logger:
    image: "rust:1-buster"
    depends_on:
      - "node"
    volumes:
      - trace:/tmp/trace
    command: "tail -f /tmp/trace/trace.fifo"
volumes:
  trace: