# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/MikeSofaer/pylons
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: GO111MODULE=on go install -v ./cmd/pylonsd/
      - run: GO111MODULE=on go install -v ./cmd/pylonscli/
      - run: pylonsd init --chain-id pylonschain
      - run: $(pylonscli keys add eugen9 <<< 11111111)
      - run: pylonsd add-genesis-account $(pylonscli keys show eugen -a) 10000000pylon,10000000eugencoin
      # pylonsd start > pylonsd.log & (sleep 10 && pylonscli tx sign create_cookbook_tx.json --from cosmos19vlpdf25cxh0w2s80z44r9ktrgzncf7zsaqey2 --chain-id pylonschain > signedCreateCookbookTx.json)
      - run: pylonsd start > pylonsd.log & (sleep 10 && GO111MODULE=on go test -v ./...)
  # test:
  #     docker:
  #       # specify the version
  #       - image: circleci/golang:1.12.5
  #     working_directory: /go/src/github.com/MikeSofaer/pylons
  #     steps:
  #       - checkout

  #       # specify any bash command here prefixed with `run: `
  #       - run: GO111MODULE=on go test -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build

