name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import, multi-seed-short)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2004
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - run: make build

  install-runsim:
    runs-on: buildjet-4vcpu-ubuntu-2004
    needs: build
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism:
    runs-on: buildjet-16vcpu-ubuntu-2004
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-nondeterminism
        run: |
          make test-sim-nondeterminism

  test-sim-multi-seed-short:
    runs-on: buildjet-16vcpu-ubuntu-2004
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display go version
        run: go version
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-multi-seed-short
        run: |
          make test-sim-multi-seed-short
